/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafeteria;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author 22PROGB07
 */
public class Precio extends javax.swing.JFrame {
    
    DefaultListModel T =new DefaultListModel();

    
        int tCoca = 0;
        int tAgua = 0;
        int tFanta = 0;
        int tMansanita = 0;
    /**
     * Creates new form Precio
     */

            
        
    public Precio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        chbCoca = new javax.swing.JCheckBox();
        chbAgua = new javax.swing.JCheckBox();
        chbFanta = new javax.swing.JCheckBox();
        chbMansanita = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnTotal = new javax.swing.JButton();
        txtPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("Ingresa La Bebida Que Quieres");

        chbCoca.setText("Coca");
        chbCoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbCocaActionPerformed(evt);
            }
        });

        chbAgua.setText("Agua");
        chbAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbAguaActionPerformed(evt);
            }
        });

        chbFanta.setText("Fanta");
        chbFanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbFantaActionPerformed(evt);
            }
        });

        chbMansanita.setText("Mansanita");
        chbMansanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbMansanitaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Orden");

        btnTotal.setBackground(new java.awt.Color(102, 255, 51));
        btnTotal.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Precios");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setText("Bebidas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbAgua)
                            .addComponent(chbMansanita)
                            .addComponent(chbFanta)
                            .addComponent(chbCoca)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chbCoca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbAgua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbFanta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chbMansanita)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnTotal))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         NewJFrame home=new NewJFrame();
            home.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        int Total = tCoca+tAgua+tFanta+tMansanita;
                txtPrecio.setText("Tu total es: "+Total);
    }//GEN-LAST:event_btnTotalActionPerformed

    private void chbCocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbCocaActionPerformed
        // TODO add your handling code here:
        String CocaTexto  = JOptionPane.showInputDialog("ingresa cuantas Haburgesas quieres: ");
        int Coca = Integer.parseInt(CocaTexto);
        if (Coca < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            tCoca = 20*Coca;
            T.addElement(this.tCoca);
            this.jList1.setModel(T);
            T.addElement(this.chbCoca.getText());
            this.jList1.setModel(T);
        }
    }//GEN-LAST:event_chbCocaActionPerformed

    private void chbAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbAguaActionPerformed
        // TODO add your handling code here:
        String AguaTexto  = JOptionPane.showInputDialog("ingresa cuantas Haburgesas quieres: ");
        int Agua = Integer.parseInt(AguaTexto);
        if (Agua < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            tAgua = 20*Agua;
            T.addElement(this.tAgua);
            this.jList1.setModel(T);
            T.addElement(this.chbAgua.getText());
            this.jList1.setModel(T);
        }
    }//GEN-LAST:event_chbAguaActionPerformed

    private void chbFantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbFantaActionPerformed
        // TODO add your handling code here:
        String FantaTexto  = JOptionPane.showInputDialog("ingresa cuantas Haburgesas quieres: ");
        int Fanta = Integer.parseInt(FantaTexto);
        if (Fanta < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            tFanta = 20*Fanta;
            T.addElement(this.tFanta);
            this.jList1.setModel(T);
            T.addElement(this.chbFanta.getText());
            this.jList1.setModel(T);
        }
    }//GEN-LAST:event_chbFantaActionPerformed

    private void chbMansanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbMansanitaActionPerformed
        // TODO add your handling code here:
        String MansanitaTexto  = JOptionPane.showInputDialog("ingresa cuantas Haburgesas quieres: ");
        int Mansanita = Integer.parseInt(MansanitaTexto);
        if (Mansanita < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            tMansanita = 20*Mansanita;
            T.addElement(this.tMansanita);
            this.jList1.setModel(T);
            T.addElement(this.chbMansanita.getText());
            this.jList1.setModel(T);
        }
    }//GEN-LAST:event_chbMansanitaActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Precio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Precio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Precio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Precio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Precio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTotal;
    private javax.swing.JCheckBox chbAgua;
    private javax.swing.JCheckBox chbCoca;
    private javax.swing.JCheckBox chbDonas;
    private javax.swing.JCheckBox chbDonas1;
    private javax.swing.JCheckBox chbDonas2;
    private javax.swing.JCheckBox chbDulces;
    private javax.swing.JCheckBox chbDulces1;
    private javax.swing.JCheckBox chbDulces2;
    private javax.swing.JCheckBox chbFanta;
    private javax.swing.JCheckBox chbMansanita;
    private javax.swing.JCheckBox chbPank;
    private javax.swing.JCheckBox chbPank1;
    private javax.swing.JCheckBox chbPank2;
    private javax.swing.JCheckBox chbRebanada;
    private javax.swing.JCheckBox chbRebanada1;
    private javax.swing.JCheckBox chbRebanada2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
