/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafeteria;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;


/**
 *
 * @author 22PROGB07
 */
public class Taqueria extends javax.swing.JFrame {
DefaultListModel J =new DefaultListModel();

    /**
     * Creates new form Cafeteriaa
     */
        int MQuesadillaB = 0;
        int MQuesadillaC = 0;
        int MQuesadillaT = 0;
        int MTacoB = 0;
        int MTacoC = 0;
        int MTacoT = 0;
        int MTortaB = 0;
        int MTortaC = 0;
        int MTortaT = 0;
        int MHamburgesaR = 0;
        int MHamburgesaP = 0 ;
        

    public Taqueria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chbTaco = new javax.swing.JCheckBox();
        chbQuesadillaB = new javax.swing.JCheckBox();
        chbTortaB = new javax.swing.JCheckBox();
        chbHamburgesaR = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        chbTacoC = new javax.swing.JCheckBox();
        chbTacoT = new javax.swing.JCheckBox();
        chbQuesadillaC = new javax.swing.JCheckBox();
        chbQuesadillaT = new javax.swing.JCheckBox();
        chbTortaC = new javax.swing.JCheckBox();
        chbTortaT = new javax.swing.JCheckBox();
        chbHamburgesaP = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setText("Menu De Comida");

        btnReset.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setText("Orden");

        jScrollPane1.setViewportView(jList1);

        txtPrecio.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setText("Precio Final De Comida");

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 255, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton2.setText("Siguente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cafeteria/taqueros-pastorero.jpg"))); // NOI18N

        chbTaco.setText("Taco De Bistek=13$");
        chbTaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTacoActionPerformed(evt);
            }
        });

        chbQuesadillaB.setText("Quesadillas De Bistek=35$");
        chbQuesadillaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbQuesadillaBActionPerformed(evt);
            }
        });

        chbTortaB.setText("Tortas De Bistek = 35$");
        chbTortaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTortaBActionPerformed(evt);
            }
        });

        chbHamburgesaR.setText("Hamburgesa De Res = 55$");
        chbHamburgesaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbHamburgesaRActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setText("Comida");

        jButton3.setBackground(new java.awt.Color(204, 204, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton3.setText("Bebidas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        chbTacoC.setText("Taco De Chorizo=13$");
        chbTacoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTacoCActionPerformed(evt);
            }
        });

        chbTacoT.setText("Taco De Tripa=13$");
        chbTacoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTacoTActionPerformed(evt);
            }
        });

        chbQuesadillaC.setText("Quesadilla De Chorizo=35$");
        chbQuesadillaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbQuesadillaCActionPerformed(evt);
            }
        });

        chbQuesadillaT.setText("Quesadilla De Tripa=35$");
        chbQuesadillaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbQuesadillaTActionPerformed(evt);
            }
        });

        chbTortaC.setText("Torta De Chorizo=35$");
        chbTortaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTortaCActionPerformed(evt);
            }
        });

        chbTortaT.setText("Torta De Tripa=35$");
        chbTortaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTortaTActionPerformed(evt);
            }
        });

        chbHamburgesaP.setText("Hamburgesa De Pollo=55$");
        chbHamburgesaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbHamburgesaPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chbTacoC)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(562, 562, 562)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chbHamburgesaR)
                                    .addComponent(chbTortaC)
                                    .addComponent(chbTortaB)
                                    .addComponent(chbTortaT)
                                    .addComponent(chbHamburgesaP)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(chbTaco)
                            .addComponent(chbTacoT)
                            .addComponent(chbQuesadillaB)
                            .addComponent(jLabel6)
                            .addComponent(chbQuesadillaC)
                            .addComponent(chbQuesadillaT)
                            .addComponent(jLabel4))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton3)))))))
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbTaco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbTacoC)
                                .addGap(5, 5, 5)
                                .addComponent(chbTacoT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbQuesadillaB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chbQuesadillaC)
                                    .addComponent(chbHamburgesaP)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(chbTortaB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbTortaC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbTortaT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbHamburgesaR)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbQuesadillaT)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReset)
                            .addComponent(jButton1)))
                    .addComponent(jLabel4))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        J.removeAllElements();
        this.jList1.setModel(J);
        J.removeAllElements();
        this.jList1.setModel(J);
        chbTortaB.setSelected(false);
        chbTortaC.setSelected(false);
        chbTortaT.setSelected(false);
        chbTaco.setSelected(false);
        chbTacoC.setSelected(false);
        chbTacoT.setSelected(false);
        chbQuesadillaB.setSelected(false);
        chbQuesadillaC.setSelected(false);
        chbQuesadillaT.setSelected(false);
        chbHamburgesaR.setSelected(false);
        chbHamburgesaP.setSelected(false);


        
        txtPrecio.setText("");


    }//GEN-LAST:event_btnResetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int Total = MTacoB+MTacoC+MTacoT+MQuesadillaB+MQuesadillaC+MQuesadillaT+MTortaB+MTortaC+MTortaT+MHamburgesaR+MHamburgesaP;
         txtPrecio.setText("Tu total es: "+Total);
         
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
                     NewJFrame home=new NewJFrame();
            home.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void chbHamburgesaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbHamburgesaRActionPerformed
        // TODO add your handling code here:
        String HamburgesaTexto  = JOptionPane.showInputDialog("ingresa cuantas Haburgesas quieres: ");
        int HamburgesaRes = Integer.parseInt(HamburgesaTexto);
        if (HamburgesaRes < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            MHamburgesaR = 55*HamburgesaRes;
            J.addElement(this.MHamburgesaR);
            this.jList1.setModel(J);
            J.addElement(this.chbHamburgesaR.getText());
            this.jList1.setModel(J);
        }

    }//GEN-LAST:event_chbHamburgesaRActionPerformed

    private void chbTortaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTortaBActionPerformed
        // TODO add your handling code here:
        String Tortatexto  = JOptionPane.showInputDialog("ingresa cuantas Tortas quieres: ");
        int TortaBistek = Integer.parseInt(Tortatexto);
        if (TortaBistek < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            MTortaB = 35*TortaBistek;
            J.addElement(this.MTortaB);
            this.jList1.setModel(J);
            J.addElement(this.chbTortaB.getText());
            this.jList1.setModel(J);
        }

    }//GEN-LAST:event_chbTortaBActionPerformed

    private void chbQuesadillaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbQuesadillaBActionPerformed
        // TODO add your handling code here:
        String Qusadillastexto  = JOptionPane.showInputDialog("ingresa cuantas Quesadillas quieres: ");
        int QusadillasBistek = Integer.parseInt(Qusadillastexto);
        if (QusadillasBistek < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            MQuesadillaB = 35*QusadillasBistek;
            J.addElement(this.MQuesadillaB);
            this.jList1.setModel(J);
            J.addElement(this.chbQuesadillaB.getText());
            this.jList1.setModel(J);
        }

    }//GEN-LAST:event_chbQuesadillaBActionPerformed

    private void chbTacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTacoActionPerformed
        // TODO add your handling code here:

        String Tacotexto  = JOptionPane.showInputDialog("ingresa cuantos Tacos quieres: ");
        int TacoBistek = Integer.parseInt(Tacotexto);
        if (TacoBistek < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            MTacoB = 13*TacoBistek;
            J.addElement(this.MTacoC);
            this.jList1.setModel(J);
            J.addElement(this.chbTaco.getText());
            this.jList1.setModel(J);
        }

    }//GEN-LAST:event_chbTacoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                Precio home=new Precio();
                home.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void chbTacoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTacoCActionPerformed
        // TODO add your handling code here:
        String Tacotexto  = JOptionPane.showInputDialog("ingresa cuantos Tacos quieres: ");
        int TacoChorizo = Integer.parseInt(Tacotexto);
        if (TacoChorizo < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            MTacoC = 13*TacoChorizo;
            J.addElement(this.MTacoC);
            this.jList1.setModel(J);
            J.addElement(this.chbTacoC.getText());
            this.jList1.setModel(J);
        }
    }//GEN-LAST:event_chbTacoCActionPerformed

    private void chbTacoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTacoTActionPerformed
        // TODO add your handling code here:
        String Tacotexto  = JOptionPane.showInputDialog("ingresa cuantos Tacos quieres: ");
        int TacoTripa = Integer.parseInt(Tacotexto);
        if (TacoTripa < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            MTacoT = 13*TacoTripa;
            J.addElement(this.MTacoT);
            this.jList1.setModel(J);
            J.addElement(this.chbTacoT.getText());
            this.jList1.setModel(J);
        }
        
    }//GEN-LAST:event_chbTacoTActionPerformed

    private void chbHamburgesaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbHamburgesaPActionPerformed
        // TODO add your handling code here:
        String HamburgesaTexto  = JOptionPane.showInputDialog("ingresa cuantas Haburgesas quieres: ");
        int HamburgesaPollo = Integer.parseInt(HamburgesaTexto);
        if (HamburgesaPollo < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            MHamburgesaP = 55*HamburgesaPollo;
            J.addElement(this.MHamburgesaP);
            this.jList1.setModel(J);
            J.addElement(this.chbHamburgesaP.getText());
            this.jList1.setModel(J);
        }
    }//GEN-LAST:event_chbHamburgesaPActionPerformed

    private void chbTortaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTortaCActionPerformed
        // TODO add your handling code here:
        String Tortatexto  = JOptionPane.showInputDialog("ingresa cuantas Tortas quieres: ");
        int TortaChorizo = Integer.parseInt(Tortatexto);
        if (TortaChorizo < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            MTortaC = 35*TortaChorizo;
            J.addElement(this.MTortaC);
            this.jList1.setModel(J);
            J.addElement(this.chbTortaC.getText());
            this.jList1.setModel(J);
        }
    }//GEN-LAST:event_chbTortaCActionPerformed

    private void chbTortaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTortaTActionPerformed
        // TODO add your handling code here:
        String Tortatexto  = JOptionPane.showInputDialog("ingresa cuantas Tortas quieres: ");
        int TortaTripa = Integer.parseInt(Tortatexto);
        if (TortaTripa < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            MTortaT = 35*TortaTripa;
            J.addElement(this.MTortaT);
            this.jList1.setModel(J);
            J.addElement(this.chbTortaT.getText());
            this.jList1.setModel(J);
        }
    }//GEN-LAST:event_chbTortaTActionPerformed

    private void chbQuesadillaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbQuesadillaCActionPerformed
        // TODO add your handling code here:
        String Qusadillastexto  = JOptionPane.showInputDialog("ingresa cuantas Tortas quieres: ");
        int QusadillasBistek = Integer.parseInt(Qusadillastexto);
        if (QusadillasBistek < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            MQuesadillaB = 35*QusadillasBistek;
            J.addElement(this.MQuesadillaB);
            this.jList1.setModel(J);
            J.addElement(this.chbQuesadillaB.getText());
            this.jList1.setModel(J);
        }
    }//GEN-LAST:event_chbQuesadillaCActionPerformed

    private void chbQuesadillaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbQuesadillaTActionPerformed
        // TODO add your handling code here:
        String Qusadillastexto  = JOptionPane.showInputDialog("ingresa cuantas Tortas quieres: ");
        int QusadillasTripa = Integer.parseInt(Qusadillastexto);
        if (QusadillasTripa < 0 ){
            JOptionPane.showMessageDialog(null, "Los campos estan becios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            MQuesadillaT = 35*QusadillasTripa;
            J.addElement(this.MQuesadillaT);
            this.jList1.setModel(J);
            J.addElement(this.chbQuesadillaT.getText());
            this.jList1.setModel(J);
        }
    }//GEN-LAST:event_chbQuesadillaTActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taqueria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taqueria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taqueria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taqueria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taqueria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox chbHamburgesaP;
    private javax.swing.JCheckBox chbHamburgesaR;
    private javax.swing.JCheckBox chbQuesadillaB;
    private javax.swing.JCheckBox chbQuesadillaC;
    private javax.swing.JCheckBox chbQuesadillaT;
    private javax.swing.JCheckBox chbTaco;
    private javax.swing.JCheckBox chbTacoC;
    private javax.swing.JCheckBox chbTacoT;
    private javax.swing.JCheckBox chbTortaB;
    private javax.swing.JCheckBox chbTortaC;
    private javax.swing.JCheckBox chbTortaT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
